### ISSUE TITLE
lazy load of resources

### ISSUE THREAD

**Issue by balmas** [alpheios-project/lexis-cs#9]
(I could have sworn I entered this issue already but I cannot find it...)

We need a way to lazy load the resources served by the various configured services.  A user who is reading Latin should not have to download the chinese dictionary, etc.

**Comment by kirlat** [comment]
How would we like lazy loading state (on/off) to be controlled? Would that be user preferences in options? Would that be the user specifying whether a Chinese support is needed, or would that be some config options of embed-lib/webextension that will be specified during initialization, or would that be anything else?

**Comment by balmas** [comment]
Well, I was thinking ideally we would just push it off to the first time the user tried to do something that required a resource that needed to be loaded.

E.g. they try to lookup a chinese word, we notice that the data is not loaded yet, so we notify them that we're going to load it, show them a loading status while it's loading, then proceed as normal.

Do you think something like this is doable?

**Comment by balmas** [comment]
This should be able to be tested with webextension qa.20200320411

Clear the cache before testing. 

First activation of Alpheios upon installation should be quick again. First lookup of a chinese word should prompt you to load the dictionary.

**Comment by balmas** [comment]
Additional changes were made to load configuration from remote server per alpheios-project/alpheios-core#140

So ready for testing now in Alpheios Reading Tools 3.1.0 build qa.20200410484

Clear the cache before testing.

First activation of Alpheios upon installation should be quick again. First lookup of a chinese word should prompt you to load the dictionary.

**Comment by monzug** [comment]
1) every time that I move to an other page on the same site, lookup or double-click does fail and I need to reload the Chinese data. can the load of the dictionary be done only one time per session?

2) my first lookup/double click does always fail because I need to upload the dictionary first. Wouldn't it be nice to prompt for loading the chinese data before failing a lookup/double click?

![chinese-load](https://user-images.githubusercontent.com/41396793/80380929-35495580-886e-11ea-9848-89b7944688d0.JPG)

**Comment by balmas** [comment]
> 1. every time that I move to an other page on the same site, lookup or double-click does fail and I need to reload the Chinese data. can the load of the dictionary be done only one time per session?

Hmm. This should be fixed. Ideally it will retain the state of the loading across tabs. @kirlat can you look into this?

**Comment by balmas** [comment]
>my first lookup/double click does always fail because I need to upload the dictionary first. Wouldn't it be nice to prompt for loading the chinese data before failing a lookup/double click?

The issue here is that we really don't know before they do a lookup if they are going to want to use chinese. So we decided on this compromise for now.

**Comment by monzug** [comment]
can we make the 'Chinese data needs to load' message more visible? I do understand that there are two reasons for a failed lookup: 1) the page language  and 2) the Chinese data not loaded yet, so both need to be displayed.  if I am not logged in yet, there are 3 messages that blend together.

**Comment by balmas** [comment]
agree. We intend eventually to refactor the notification component so that we have more flexibility and options but @kirlat maybe in the meantime we can add another color variant for this? What do you think?

**Comment by monzug** [comment]
I was thinking like we do for the mouse over event

**Comment by kirlat** [comment]
> > 1. every time that I move to an other page on the same site, lookup or double-click does fail and I need to reload the Chinese data. can the load of the dictionary be done only one time per session?
> 
> Hmm. This should be fixed. Ideally it will retain the state of the loading across tabs. @kirlat can you look into this?

@monzug testing found a flaw in the business logic of CEDICT service that I overlooked. CEDICT does not initialize itself waiting for the first morph request to come. When request arrives and CEDICT is uninitiated (even if CEDICT data is in the IndexedDB), it respond with the "uninitialized" message. I think that instead of that, when a new request comes in and CEDICT is uninitialized but the data is already loaded, it should initialize itself and respond with the morph data. An "uninitialized" message should be returned only when no CEDICT data is loaded.

Does this make sense?

**Comment by balmas** [comment]
Yes that makes sense.

**Comment by kirlat** [comment]
It should be solved with the latest updates of the `lexis-cs` and `alpheios-core`.

**Comment by balmas** [comment]
this one can be tested in Alpheios Components 3.3.0-qa.20200504341

**Comment by monzug** [comment]
Safari App Extension 3.1.0 build qa.20200513448
Alpheios Components 3.3.0-qa.20200513442

we have a more visible message for loading the Chinese database. Thanks!

I did also some testing on https://www.sohu.com and https://www.baidu.com/ (the most popular search engine).  in this site, when I go from page one to page 4, alpheios is active but I do not have the toolbar anymore. I was just playing around with Chinese, not sure if this is part of the scope of the chinese project.

https://www.baidu.com/s?wd=涉港草案将审议%20林郑月娥发声明&pn=0&oq=涉港草案将审议%20林郑月娥发声明&tn=baidutop10&ie=utf-8&usm=1&rsv_idx=2&rsv_pq=93f74baa000269c3&rsv_t=38e1IsOYRDwMsxv2RzIX3pJlrReBBksdUkvpEiH9qAVSx9Ft6PFAHiCgeIuX9wr2EA

![Screen Shot 2020-05-22 at 4 16 25 PM](https://user-images.githubusercontent.com/41396793/82677024-a7337580-9c47-11ea-9bf4-57bf3ac438f4.png)

**Comment by balmas** [comment]
> I did also some testing on https://www.sohu.com and https://www.baidu.com/ (the most popular search engine). in this site, when I go from page one to page 4, alpheios is active but I do not have the toolbar anymore. I was just playing around with Chinese, not sure if this is part of the scope of the chinese project.

I have seen some intermittent problems with other languages with this as well. I think it needs some investigation. I will make it a new issue.

**Comment by monzug** [comment]
ah ok. not sure if it's a pandora's box!!!

**Comment by balmas** [comment]
@monzug as the issue with switching sites is now #376 can we verify this one? Thanks!
